language: smalltalk

services:
  - docker

before_script:
  - docker pull rabbitmq:3
  - docker run -d --name rabbitmq-for-tests -p5672:5672 rabbitmq:3
  - docker ps -a

os:
  - linux

smalltalk:
  - Pharo32-7.0
  - Pharo64-7.0
  - Pharo32-8.0
  - Pharo64-8.0

matrix:
  allow_failures:
    - smalltalk: Pharo32-8.0
    - smalltalk: Pharo64-8.0
  fash_finish: true
