language: smalltalk

sudo: required

services:
  - docker

before_script:
  - docker pull rabbitmq:3
  - docker run -d --name rabbitmq-for-tests -p5672:5672 rabbitmq:3
  - docker ps -a
  - docker exec -it rabbitmq-for-tests bash
  - rabbitmq-diagnostics check_running
  - exit

after_failure: 
  - sleep 5         
  - docker inspect --format='{{.LogPath}}' rabbitmq-for-tests | sudo xargs cat

os:
  - linux

smalltalk:
  - Pharo32-7.0
  - Pharo64-7.0
  - Pharo32-8.0
  - Pharo64-8.0

matrix:
  allow_failures:
    - smalltalk: Pharo32-8.0
    - smalltalk: Pharo64-8.0
  fash_finish: true
