language: smalltalk

sudo: required

services:
  - docker

before_script:
  - docker pull rabbitmq:3
  - docker run -d --name rabbit-tests -p5672:5672 rabbitmq:3
  - docker ps -a
  - docker exec rabbit-tests rabbitmqctl await_startup

after_failure: 
  - docker inspect --format='{{.LogPath}}' rabbit-tests | sudo xargs cat

os:
  - linux

smalltalk:
  - Pharo32-7.0
  - Pharo64-7.0
  - Pharo32-8.0
  - Pharo64-8.0

matrix:
  allow_failures:
    - smalltalk: Pharo32-8.0
    - smalltalk: Pharo64-8.0
  fash_finish: true
